name: CI/CD Pipeline for Clustering App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t clustering-app .

      - name: Push Docker image to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag clustering-app ${{ secrets.DOCKER_USERNAME }}/clustering-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/clustering-app:latest
